String? dummytxt =
"""Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.""";
List<String> educationLevels = [
  "8th Passed",
  "10+2 or Equivalent",
  "Diploma in any Discipline",
  "Doctorate in any Discipline",
  "Graduate",
  "ITI/Certificate Course",
  "Illiterate",
  "M.Phil.",
  "Not Specified / NA",
  "PG ",
];
List<String> places = [
  "Alappuzha",
  "Kottayam",
  "Manjeri",
  "Thalassery",
  "Thrippunithura",
  "Ponnani",
  "Vatakara",
  "Kanhangad",
  "Payyanur",
  "Koyilandy",
  "Parappanangadi",
  "Kalamassery",
  "Kodungallur",
  "Neyyattinkara",
  "Tanur",
  "Kayamkulam",
  "Malappuram",
  "Guruvayur",
  "Thrikkakkara",
  "Wadakkancherry",
  "Nedumangad",
  "Kondotty",
  "Tirurangadi",
  "Tirur",
  "Panoor",
  "Kasaragod",
  "Feroke",
  "Kunnamkulam",
  "Ottappalam",
  "Tiruvalla",
  "Thodupuzha",
  "Perinthalmanna",
  "Chalakudy",
  "Payyoli",
  "Koduvally",
  "Mananthavady",
  "Changanassery",
  "Mattanur",
  "Punalur",
  "Nilambur",
  "Cherthala",
  "Sultan Bathery",
  "Maradu",
  "Kottakkal",
  "Taliparamba",
  "Shornur",
  "Pandalam",
  "Kattappana",
  "Cherpulassery",
  "Mukkam",
  "Iritty",
  "Valanchery",
  "Varkala",
  "Nileshwaram",
  "Chavakkad",
  "Kothamangalam",
  "Pathanamthitta",
  "Attingal",
  "Paravur",
  "Ramanattukara",
  "Mannarkkad",
  "Erattupetta",
  "Sreekandapuram",
  "Angamaly",
  "Chittur-Thathamangalam",
  "Kalpetta",
  "North Paravur",
  "Haripad",
  "Muvattupuzha",
  "Kottarakara",
  "Kuthuparamba",
  "Adoor",
  "Irinjalakuda",
  "Pattambi",
  "Anthoor",
  "Perumbavoor",
  "Piravom",
  "Ettumanoor",
  "Mavelikkara",
  "Karunagappalli",
  "Eloor",
  "Chengannur",
  "Vaikom",
  "Aluva",
  "Pala",
  "Koothattukulam"
];



List<String> countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
].toSet().toList();

List<String> bloodGroups = [
  "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-",
  "A1+", "A1-", "A2+", "A2-", "A1B+", "A1B-", "A2B+", "A2B-",
  "Bombay Blood Group", "INRA", "Kell-null", "Duffy-null", "Hh-null"
].toSet().toList();

List<Map<String, dynamic>> serviceType = [
  {
    "title": "Cars",
    'img': 'assets/svg/cardriver.svg',
  },
  {
    "title": "Heavy Vehicles",
    'img': 'assets/svg/truck.svg',
  },
  {
    "title": "Motor Bikes",
    'img': 'assets/svg/bikes.svg',
  },
];

List<Map<String, dynamic>> otherserviceType = [
  {
    "title": "Towing",
    'img': 'assets/svg/towing.svg',
  },
  {
    "title": "Fuel",
    'img': 'assets/svg/fuel.svg',
  },
  {
    "title": "Accident",
    'img': 'assets/svg/carcrash.svg',
  },

  {
    "title": "Delivery",
    'img': 'assets/svg/foodservice.svg',
  },
];

List<String> indianStates = [
  "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh",
  "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka",
  "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram",
  "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana",
  "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal"
].toSet().toList();

